conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.home, name='home'),
    path('new/<int:pk>/', views.new_conversation, name="new"),
    path("inbox", views.inbox, name="inbox"),
    path("detail/<int:pk>/", views.detail_inbox, name="detail"),
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_page, name='login'),
    path("logout/", views.logout_view, name="logout"),
    path("new-item/", views.new_item, name="new-item"),
    path('edit-item/<int:pk>/', views.edit_items, name='edit-items'),
    path("detail/<pk>/", views.detail, name="detail"),
    path("delete/<int:pk>/", views.delete_view, name="delete"),
    path('search/', views.search, name='search'),
]

marketng/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('conversation/', include('conversation.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=150)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.TextField()
    quantity = models.IntegerField()
    images = models.ImageField(upload_to='images')
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='products', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)



    def __str__(self):
        return self.name

core/forms.py
from django import forms
from django.contrib.auth.models import User

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import Product


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'First Name',
        'class': 'form-control'
    }))

    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Last Name',
        'class': 'form-control'
    }))

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': 'form-control'
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Email',
        "class": 'form-control'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': 'form-control'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password',
        'class': 'form-control'
    }))


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': 'form-control'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': 'form-control'
    }))


class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['category', 'name', 'price', 'description', 'is_sold', 'quantity', 'images']

core/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404

from .models import Product
from .forms import RegisterForm, LoginForm, AddProductForm


# Create your views here.
def home(request):
    products = Product.objects.all()

    context = {'products': products}
    return render(request, 'core/home.html', context)


def signup(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:login')
    else:
        form = RegisterForm()

    context = {'form': form}
    return render(request, 'core/signup.html', context)


def login_page(request):
    form = LoginForm

    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('core:home')
    context = {'form': form}
    return render(request, 'core/login.html', context)


def logout_view(request):
    logout(request)
    return redirect('core:home')


@login_required
def new_item(request):
    form = AddProductForm()

    if request.method == 'POST':
        form = AddProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.created_by = request.user
            product.save()
            return redirect('core:home')
        else:
            print("Form errors:", form.errors)
    context = {
        'form': form,
        'title': 'Add New Item'
    }
    return render(request, 'core/form.html', context)


@login_required
def edit_items(request, pk):
    product = get_object_or_404(Product, pk=pk, created_by=request.user)
    form = AddProductForm(instance=product)
    if request.method == 'POST':
        form = AddProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('core:home')

    context = {
        'form': form,
        'product': product,
        'title': 'Edit Items',
    }
    return render(request, 'core/form.html', context)


def detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    related_products = Product.objects.filter(category=product.category).exclude(pk=pk)

    context = {
        'product': product,
        'related_products': related_products,
    }
    return render(request, 'core/detail.html', context)


def delete_view(request, pk):
     product = get_object_or_404(Product, pk=pk, created_by=request.user)
     if request.method == "POST":
        product.delete()
        return redirect('core:home')

     context = {
         'product': product
     }
     return render(request, 'core/delete.html', context)


def search(request):
    query = request.GET.get('query', '')
    products = Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))

    context = {
        'query': query,
        'products': products,
    }
    return render(request, 'core/search.html', context)

templates/core/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %} | Market NG</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
        <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container-fluid container">
    <a class="navbar-brand" href="{% url 'core:home' %}">Market NG</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'core:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link active dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            @{{request.user}}
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Dashboard</a></li>
            <li><a class="dropdown-item" href="#">Profile</a></li>
            <li><a class="dropdown-item" href="{% url 'conversation:inbox' %}">Inbox</a></li>
            <li><a class="dropdown-item" href="{% url 'core:new-item' %}">Add Item</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'core:logout' %}">Logout</a></li>
          </ul>
          {% else %}
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'core:signup' %}">SignUp</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'core:login' %}">Login</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" role="search" action="{% url 'core:search' %}" method="GET">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query" value="{{ query }}">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>


    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/core/delete.html
    {% extends "core/base.html" %}

    {% block title %}Delete{% endblock title %}

    {% block content %}
    <h1>Delete</h1>
        <form action="" method="POST">
            {% csrf_token %}

            <p class="my-5">Are you sure that you want to delete <strong>"{{ product.name }}"</strong>?</p>

            <a href="{% url 'core:detail' product.pk %}" class="btn btn-success">Back</a>
            <button type="submit" class="btn btn-danger">Yes, Delete</button>
        </form>

    {% endblock content %}

templates/core/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ product.name }} Detail{% endblock title %}

{% block content %}

    <h1>{{ product.name }} - Detail Page</h1>

    <div class="card mb-3" style="max-width: 90%;">
      <div class="row g-0">
        <div class="col-md-5">
          <img src="{{ product.images.url }}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-7">
          <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5><br>
            <p class="card-text">${{ product.price }}</p><br>
            <p class="card-text"><strong>Description:</strong><br>{{ product.description }}</p>

            <br>
            <hr>

            {% if request.user == product.created_by %}
              <a href="{% url 'core:edit-items' product.pk %}" class="btn btn-success">Edit</a>
            <a href="{% url 'core:delete' product.pk %}" class="btn btn-danger">Delete</a>

            {% else %}
              <a href="{% url 'conversation:new' product.pk %}" class="btn btn-primary">Contact Seller</a>

            {% endif %}

          </div>
        </div>
      </div>
    </div>

        <h1>Related Products</h1>

    <div class="row">
      {% if related_products %}
        {% for product in related_products %}
        <div class="col">
            <div class="card" style="width: 18rem;">
              <img src="{{ product.images.url }}" class="card-img-top" alt="..." height="250;">
              <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">${{ product.price }}</p>
                <a href="{% url 'core:detail' product.pk %}" class="btn btn-primary">View</a>


              </div>
            </div>
        </div>

        {% endfor %}
      {% else %}
        <p>There is no related products for this category</p>
      {% endif %}
    </div>



{% endblock content %}

templates/core/form.html
{% extends "core/base.html" %}

{% block title %}New Product{% endblock title %}

{% block content %}
    <h1>{{ title }}</h1>

    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-danger">{{ title }}</button>
    </form>


{% endblock content %}

templates/core/home.html
{% extends 'core/base.html' %}

{% block title %}Home{% endblock title%}

{% block content %}
        <h1 style="margin: 50px 0;">Market NG</h1>
<div class="row">
    {% for product in products %}
    <div class="col">
        <div class="card" style="width: 18rem;">
          <img src="{{ product.images.url }}" class="card-img-top" alt="..." width="300" height="300">
          <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">$ {{ product.price }}</p>
            <p></p>
            <a href="{% url 'core:detail' product.pk %}" class="btn btn-primary">Details</a>
            {% if product.created_by == request.user %}
              <a href="{% url 'core:edit-items' product.pk %}" class="btn btn-success">Edit</a>
            {% endif %}
          </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}

templates/core/login.html
{% extends 'core/base.html' %}

{% block title%}Login{% endblock title %}

{% block content %}
    <h1>Login</h1>

    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Login</button>
    </form>
<br>
    <p>don't have an account? <a href="{% url 'core:signup' %}">signup</a></p>


{% endblock content %}

templates/core/search.html
    {% extends "core/base.html" %}

{% block title %}Search{% endblock title %}

{% block content %}


{% if query %}
    <h1>Search Results for "{{ query }}"</h1>
{% else %}
    <h1>Find Items</h1>
{% endif %}


    <div class="py-5 bg-body-tertiary">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <!-- looping over the item -->
                {% if products %}
                    {% for product in products %}
                    <div class="col">
                        <div class="card shadow-sm">
                            <img src="{{ product.images.url }}" alt="" width="100%" height="225">
                            <div class="card-body">
                                <p class="card-text"> {{ product.name }} </p>
                                <p class="card-text">$ {{ product.price }}</p>
                                <p class="card-text">{{ product.description }}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a href="{% url 'core:detail' product.id %}" type="button"
                                           class="btn btn-sm btn-outline-secondary">View</a>
                                        <button type="button" class="btn btn-sm btn-outline-secondary">Buy Now</button>
                                        <!-- add to cart and take the user to checkout page-->
                                    </div>
                                    <small class="text-body-secondary">@ {{ product.created_by.username }} </small>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <!-- endfor -->
                {% else %}
                <p>No product was found</p>
                {% endif %}
            </div>
        </div>
    </div>

    {% endblock content %}

templates/core/signup.html
{% extends "core/base.html" %}

{% block title%}Signup{% endblock title %}

{% block content %}

<h1>Signup</h1>

  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Signup</button>
  </form>


{% endblock content %}